# Generated by Django 4.1.4 on 2022-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, choices=[('Çin', 'Çin'), ('ABŞ', 'ABŞ'), ('Türkiyə', 'Türkiyə')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
