# Generated by Django 4.1.4 on 2022-12-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, null=True)),
                ('first_time', models.TimeField()),
                ('last_time', models.TimeField()),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
                ('country', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contact.country')),
            ],
        ),
    ]
